<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>28a31714-c11f-468b-92ef-b7653d0daa09</elementGuidId>
    <imagePath></imagePath>
    <name>input_inStock</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/label[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.form-check-input</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'in_stock') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="In stock"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>in_stock</value>
        <webElementGuid>f023589b-7845-441d-9bcd-d8ea5a773c14</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>f023589b-7845-441d-9bcd-d8ea5a773c14</webElementGuid>
    </webElementProperties>
</WebElementEntity>