<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f58b9898-96ff-4317-9b40-40508cc7ce99</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsungGalaxyS23Ultra</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item in-stock products__item_3-in-row"]:nth-child(1) [class="products__image"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/samsung-galaxy-s23-ultra-smartview-cases') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Samsung Galaxy S23 Ultra"i] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/samsung-galaxy-s23-ultra-smartview-cases</value>
        <webElementGuid>c0391ea6-167b-449d-b820-09432fe68fff</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>c0391ea6-167b-449d-b820-09432fe68fff</webElementGuid>
    </webElementProperties>
</WebElementEntity>