<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>67e9e328-49b0-4dad-84ea-6235c24d0a3f</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsungGalaxyS23UltraSmartviewCases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/samsung-galaxy-s23-ultra-smartview-cases?sort=price') and equals(@text,'Samsung Galaxy S23 Ultra Smartview Cases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^Samsung Galaxy S23 Ultra Smartview Cases$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/samsung-galaxy-s23-ultra-smartview-cases?sort=price</value>
        <webElementGuid>f023589b-7845-441d-9bcd-d8ea5a773c14</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy S23 Ultra Smartview Cases</value>
        <webElementGuid>f023589b-7845-441d-9bcd-d8ea5a773c14</webElementGuid>
    </webElementProperties>
</WebElementEntity>