<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f2438ad-bf01-436b-8655-281f42c3589e</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsungGalaxyZfold4SiliconCover</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(2) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/samsung-galaxy-z-fold4-silicon-cover') and equals(@text,'Samsung Galaxy Z Fold4 Silicon Cover')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^Samsung Galaxy Z Fold4 Silicon Cover$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/samsung-galaxy-z-fold4-silicon-cover</value>
        <webElementGuid>ccce5d2c-d1c3-4f15-b32c-e0b0642476cc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy Z Fold4 Silicon Cover</value>
        <webElementGuid>ccce5d2c-d1c3-4f15-b32c-e0b0642476cc</webElementGuid>
    </webElementProperties>
</WebElementEntity>