<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6a0f34dc-8a69-465f-8c57-8883492897b1</elementGuidId>
    <imagePath></imagePath>
    <name>checkbox_receiveMarketingInfo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="PrivateSwitchBase-input css-1m9pwf3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'receive_marketing_info') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Email me with news and offers"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>receive_marketing_info</value>
        <webElementGuid>c0e2ef48-35d4-459f-ac93-794aedfa9ec6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>c0e2ef48-35d4-459f-ac93-794aedfa9ec6</webElementGuid>
    </webElementProperties>
</WebElementEntity>