<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a296d7d1-626c-4cca-b3ef-6925c8dc3554</elementGuidId>
    <imagePath></imagePath>
    <name>link_productDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[3]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_productDetails_class}"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-pro') and equals(@text,'iPhone 15 Pro')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_productDetails_internalRoleLinkName}"s] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-pro</value>
        <webElementGuid>cbff9b27-8308-40fb-9cb9-616e06e1a7d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 Pro</value>
        <webElementGuid>cbff9b27-8308-40fb-9cb9-616e06e1a7d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>