<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09825a68-caf8-4238-8b6e-df0fdb76edaf</elementGuidId>
    <imagePath></imagePath>
    <name>link_dynamicObject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[3]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_dynamicObject_class}"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-silicone-case-with-magsafe') and equals(@text,'iPhone 15 Silicone Case with MagSafe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_dynamicObject_internalRoleLinkName}"s] &gt;&gt; nth=${link_dynamicObject_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-silicone-case-with-magsafe</value>
        <webElementGuid>f19c24a9-2263-4a11-91c2-f5fd9e1216b3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 Silicone Case with MagSafe</value>
        <webElementGuid>f19c24a9-2263-4a11-91c2-f5fd9e1216b3</webElementGuid>
    </webElementProperties>
</WebElementEntity>