<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2a61de3-65da-4289-8118-88fda382e4ab</elementGuidId>
    <imagePath></imagePath>
    <name>button_addToCart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${button_addToCart_class}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Add to cart') and equals(@type,'button') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="${button_addToCart_internalHasText}"i &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>d7484116-4c8d-42c0-bec5-65ab733ac0bf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>d7484116-4c8d-42c0-bec5-65ab733ac0bf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>d7484116-4c8d-42c0-bec5-65ab733ac0bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>