<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5ef46718-b9c2-44b2-9266-9b94525f35ef</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cart-header cart-header_active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'4')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>4</value>
        <webElementGuid>c8738ec6-efc4-4f1a-a27e-e7f7447c2a7f</webElementGuid>
    </webElementProperties>
</WebElementEntity>