<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6a6e8a97-b070-4246-b7f9-181813bc48b9</elementGuidId>
    <imagePath></imagePath>
    <name>link_k cellphone shop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mars-logo-row__logo"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'K Cellphone Shop')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="K Cellphone Shop"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>K Cellphone Shop</value>
        <webElementGuid>72648584-1419-4f30-b461-1d22dca0feb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>