<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0cbda31e-a421-47b2-8162-f15c1f1a06f2</elementGuidId>
    <imagePath></imagePath>
    <name>link_productDetail</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="swiper-slide\ products-slider__slide"]:nth-child(3) [class="products-slider__product-title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-pro') and equals(@text,'iPhone 15 Pro')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="iPhone 15 Pro"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-pro</value>
        <webElementGuid>c5b4bf20-b89f-415b-940d-c02e9d1031e7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 Pro</value>
        <webElementGuid>c5b4bf20-b89f-415b-940d-c02e9d1031e7</webElementGuid>
    </webElementProperties>
</WebElementEntity>