<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9fb9a60c-322a-46af-beba-126d79017a25</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsung</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/nav[1]/ul[2]/li[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class=""]:nth-child(2) &gt; div &gt; [class="title"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/category/samsung') and equals(@text,'Samsung')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Samsung"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/category/samsung</value>
        <webElementGuid>9af18a88-1944-44c7-8996-6d2d5a9c6ff4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung</value>
        <webElementGuid>9af18a88-1944-44c7-8996-6d2d5a9c6ff4</webElementGuid>
    </webElementProperties>
</WebElementEntity>