<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4b173f3b-f4c6-4141-91e3-7569e3de4d57</elementGuidId>
    <imagePath></imagePath>
    <name>span_continueToShipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]/span[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButton-startIcon\ MuiButton-iconSizeLarge\ css-wth0qt"] &gt; [class="MuiSvgIcon-root\ MuiSvgIcon-fontSizeMedium\ css-vubbuv"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'LocalShippingIcon')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Continue to shipping"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>LocalShippingIcon</value>
        <webElementGuid>513375a9-f612-4d82-be06-61be38d479c3</webElementGuid>
    </webElementProperties>
</WebElementEntity>