<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5b9a1b6d-cd66-4d94-b05d-2725e859880f</elementGuidId>
    <imagePath></imagePath>
    <name>button_ContinueToPayment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ css-1hw9j7s"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO PAYMENT')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Continue to payment"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO PAYMENT</value>
        <webElementGuid>bfcb8221-8b0b-455f-9b9f-41b7e99c5a9a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>bfcb8221-8b0b-455f-9b9f-41b7e99c5a9a</webElementGuid>
    </webElementProperties>
</WebElementEntity>