<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f54d331-d3d1-46b0-9925-e93653633129</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsungGalaxyZfold5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item in-stock products__item_3-in-row"]:nth-child(2) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/ss-galaxy-z-fold5?category=121') and equals(@text,'Samsung Galaxy Z Fold5')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Samsung Galaxy Z Fold5"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/ss-galaxy-z-fold5?category=121</value>
        <webElementGuid>45b1cb65-a6fa-4d69-b897-b7dbe54f90ab</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy Z Fold5</value>
        <webElementGuid>45b1cb65-a6fa-4d69-b897-b7dbe54f90ab</webElementGuid>
    </webElementProperties>
</WebElementEntity>